### PR TITLE
Added a bit of Doc for ActionPage , AddCampaignTile , CampaignSelecti…

### PR DESCRIPTION
**Pull request by SoutrikDas**
# Description

No issue was solved , Just added some documentation for these widgets 

- CampaignSelectionTile
- AddCampaignTile
- ActionPage

Documentation gif

### CODE REVIEW

**Comment by JElgar** [comment]
Great thank you @SoutrikDas! Are you generating any documentation with this (like an html file or something)? If so how?

**Review by JElgar — APPROVED** [review]

**Comment by SoutrikDas** [comment]
@JElgar 
Download dartdoc to generate html documentation from comments  
```dart
flutter pub global activate dartdoc
```
you can run `dartdoc` from  the project directory to generate the html files , after which you can manually open each file , but if you want a search function , you will have to install `dhttpd` like so 

```dart
flutter pub global activate dhttpd
```
Then use `dhttpd --path doc/api` ,  then go to `http://localhost:8080/` in your browser of choice 
and it will show you the same html files , but now you can search 
[Here is a gif ](https://slack-files.com/T011NB7E8R1-F01DHNGMN9E-5cbb708a33) where 

- first use `dartdoc` to generate files 
- then use `dhttpd --path doc/api`  to generate the server 
- then I should have typed `http://localhost:8080/` in the browser but I skipped this in the gif 


For effective ways to document check [their official page](https://dart.dev/guides/language/effective-dart/documentation)

**Comment by JElgar** [comment]
Amazing thank you Soutrik that's super helpful, can you shove that in the read me?

**Review by JElgar — APPROVED** [review]
Thank you for docs @SoutrikDas.
Docs can be found here: https://github.com/now-u/now-u-app/wiki/Getting-Started

**Pull request merged**
